### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [bw89arag/intro-data-capstone-biodiversity#1]
**Presentation / Analysis Document (3/4)**
Great job analyzing your code in these slides. I liked how you made an observation of each output while citing the numbers. It might have been nice to include an objective of your analysis or explain the impact of your outputs. What suggestions would you make based on the data?

**Code Accuracy (4/4)**
Your Python code is accurate for matplotlib plots, data analysis, and hypothesis testing. Accurate calculation of minimum detectable size, sample size determination in Foot & Mouth disease analysis was also included. Good job!

**Understanding Testing (4/4)**
You stated the hypothesis, ran hypothesis testing and stated the results, and interpreted your findings. Good job here!

---

Overall, your code appeared very clean and your presentation was well-formatted. I would suggest translating your code into a Jupyter notebook rather than into a .txt file to review and analyze output if you would like to at a later point!

**Comment by bw89arag** [comment]
Thanks for the feedback, Navierula! Appreciate it.

Have a nice day, Bastian
